#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["numpy==2.5.3", "scipy==1.18.1", "matplotlib==3.11.1"]
# ///
"""Generate an adaptive Voronoi mesh and an apart point-location tree."""

from __future__ import annotations

import argparse
import csv
import json
import os
import tempfile
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", str(Path(tempfile.gettempdir()) / "apart-matplotlib"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.collections import PolyCollection
from matplotlib.colors import LinearSegmentedColormap, LogNorm
from matplotlib.patches import ConnectionPatch, Rectangle
from scipy.spatial import Voronoi

from point_location import PointLocationTree, area, bisector, centroid, clip, locate
from sql_case import case_sql


OUTPUT = Path(__file__).resolve().parent
SEED = 20260912
CELL_COUNT = 1000
WIDTH, HEIGHT = 12.0, 8.0
DOMAIN = np.array([[0.0, 0.0], [WIDTH, 0.0], [WIDTH, HEIGHT], [0.0, HEIGHT]])


def channel(x):
    return 4.0 + 1.55 * np.sin(2.0 * np.pi * (x - 0.5) / WIDTH)


def polygons_from_sites(sites):
    neighbors = [set() for _ in sites]
    for a, b in Voronoi(sites).ridge_points:
        neighbors[a].add(b)
        neighbors[b].add(a)
    polygons = []
    for a, adjacent in enumerate(neighbors):
        polygon = DOMAIN.copy()
        for b in sorted(adjacent):
            normal, threshold = bisector(sites, a, b)
            polygon = clip(polygon, -normal, -threshold)
        polygons.append(polygon)
    return polygons


def make_grid():
    rng = np.random.default_rng(SEED)
    accepted = []
    while len(accepted) < CELL_COUNT:
        points = rng.uniform([0.0, 0.0], [WIDTH, HEIGHT], size=(2048, 2))
        distance = points[:, 1] - channel(points[:, 0])
        density = 0.13 + 0.87 * np.exp(-0.5 * (distance / 0.40) ** 2)
        accepted.extend(points[rng.random(len(points)) < density])
    sites = np.asarray(accepted[:CELL_COUNT])
    # A few Lloyd steps improve cell shape while retaining the density contrast.
    for _ in range(3):
        sites = np.asarray([centroid(p) for p in polygons_from_sites(sites)])
    # Spatial numbering makes nearby IDs easier to find in the illustration.
    sites = sites[np.lexsort((sites[:, 1], sites[:, 0]))]
    return sites, polygons_from_sites(sites)


def write_data(sites, polygons, locator):
    tree = locator.tree
    (OUTPUT / "tree.json").write_text(json.dumps(tree, separators=(",", ":")) + "\n")
    features = []
    for cell_id, (site, polygon) in enumerate(zip(sites, polygons)):
        features.append({
            "type": "Feature",
            "id": cell_id,
            "properties": {"cell_id": cell_id, "site": site.tolist(), "area": area(polygon)},
            "geometry": {"type": "Polygon", "coordinates": [[*polygon.tolist(), polygon[0].tolist()]]},
        })
    geojson = {"type": "FeatureCollection", "bbox": [0, 0, WIDTH, HEIGHT], "features": features}
    (OUTPUT / "grid.geojson").write_text(json.dumps(geojson, separators=(",", ":")) + "\n")

    def sql_list(value):
        if isinstance(value, list):
            return "[" + ",".join(sql_list(v) for v in value) + "]"
        if value is None:
            return "NULL::INTEGER"
        return repr(value)

    sql = (
        "-- Generated by generate.py. Cell IDs are 0..999; outside is NULL.\n"
        "LOAD apart;\n\nCREATE OR REPLACE MACRO unstructured_grid_tree() AS {\n"
        + "    weights: " + sql_list(tree["weights"]) + "::DOUBLE[][],\n"
        + "    thresholds: " + sql_list(tree["thresholds"]) + "::DOUBLE[],\n"
        + "    children: " + sql_list(tree["children"]) + "::BIGINT[][],\n"
        + "    values: " + sql_list(tree["values"]) + "\n};\n\n"
        "CREATE OR REPLACE MACRO locate_cell(x, y) AS\n"
        "    decision_tree(unstructured_grid_tree(), x::DOUBLE, y::DOUBLE);\n"
    )
    (OUTPUT / "grid.sql").write_text(sql)
    (OUTPUT / "grid_case.sql").write_text(case_sql(tree))
    stats = {
        "seed": SEED,
        "cells": len(polygons),
        "domain": {"x": [0, WIDTH], "y": [0, HEIGHT]},
        "coordinate_system": "unitless Cartesian; not geographic longitude/latitude",
        "internal_nodes": len(tree["weights"]),
        "distinct_leaf_values": len(tree["values"]),
        "interior_leaf_occurrences": len(locator.leaf_depths),
        "min_interior_decisions": min(locator.leaf_depths),
        "max_interior_decisions": max(locator.leaf_depths),
        "mean_decisions_uniform_domain": locator.weighted_depth / (WIDTH * HEIGHT),
        "outside_value": None,
        "boundary_rule": "Closed domain; shared edges follow the >= branch in double precision.",
    }
    stats["construction"] = locator.construction
    stats["geometry"] = "clipped Voronoi cells of the stored generating sites"
    stats["coefficient_format"] = "DOUBLE coefficients in tree.json and grid.sql"
    (OUTPUT / "metadata.json").write_text(json.dumps(stats, indent=2) + "\n")
    return stats


def draw_grid(polygons, tree):
    background, ink = "#f7f4ec", "#173b49"
    cmap = LinearSegmentedColormap.from_list(
        "estuary", ["#174e64", "#388d96", "#9cc5b3", "#edd9aa", "#d79061"]
    )
    areas = np.array([area(p) for p in polygons])
    norm = LogNorm(vmin=areas.min(), vmax=areas.max())
    colors = cmap(norm(areas))
    plt.rcParams.update({
        "font.family": "DejaVu Sans", "font.size": 13,
        "text.color": ink, "axes.labelcolor": ink, "axes.labelsize": 15,
    })
    fig, (main, zoom) = plt.subplots(
        1, 2, figsize=(13.5, 6), width_ratios=(1.5, 1),
        layout="compressed", facecolor=background,
    )

    def draw(ax, width):
        collection = PolyCollection(polygons, facecolors=colors, edgecolors=ink, linewidths=width)
        ax.add_collection(collection)
        ax.set_aspect("equal")
        ax.set_facecolor(background)
        ax.tick_params(colors=ink, length=4, labelsize=13)
        for spine in ax.spines.values():
            spine.set_color(ink)
            spine.set_linewidth(0.7)
        return collection

    draw(main, 0.42)
    draw(zoom, 0.7)
    main.set(xlim=(0, WIDTH), ylim=(0, HEIGHT), xlabel="x", ylabel="y")
    samples = [("A", 2.4, 5.50), ("B", 5.8, 4.25), ("C", 9.7, 2.50)]
    zx, zy, radius = samples[1][1], samples[1][2], 0.65
    zoom.set(xlim=(zx - radius, zx + radius), ylim=(zy - radius, zy + radius))
    zoom.set_title("Detail around B", fontsize=15, pad=8)
    for cell_id, polygon in enumerate(polygons):
        cx, cy = centroid(polygon)
        if zx - radius + 0.07 < cx < zx + radius - 0.07 and zy - radius + 0.07 < cy < zy + radius - 0.07:
            zoom.text(cx, cy, str(cell_id), ha="center", va="center", fontsize=10, color=ink, clip_on=True)

    rectangle = Rectangle((zx - radius, zy - radius), 2 * radius, 2 * radius,
                          fill=False, edgecolor=ink, linewidth=1.5, linestyle=(0, (4, 3)))
    main.add_patch(rectangle)
    fig.add_artist(ConnectionPatch(
        (zx + radius, zy + radius), (0, 1), coordsA="data", coordsB="axes fraction",
        axesA=main, axesB=zoom, color=ink, linewidth=0.8, alpha=0.35,
    ))
    results = []
    for name, x, y in samples:
        cell_id = locate(tree, x, y)
        results.append((name, x, y, cell_id))
        polygon = polygons[cell_id]
        for ax in [main, zoom]:
            ax.add_collection(PolyCollection([polygon], facecolors="none", edgecolors="#ffffff", linewidths=2.4))
            ax.scatter([x], [y], s=95 if ax is main else 60, facecolor=ink, edgecolor="white", linewidth=1.2, zorder=5)
        main.annotate(name, (x, y), xytext=(9, 10), textcoords="offset points", weight="bold", fontsize=14,
                      bbox={"boxstyle": "round,pad=0.18", "facecolor": background, "edgecolor": "none", "alpha": 0.92})

    colorbar = fig.colorbar(
        plt.cm.ScalarMappable(norm=norm, cmap=cmap), ax=[main, zoom],
        orientation="horizontal", fraction=0.06, pad=0.06, shrink=0.65, aspect=45,
    )
    ticks = [value for value in (0.01, 0.03, 0.1, 0.3) if norm.vmin <= value <= norm.vmax]
    colorbar.set_ticks(ticks, labels=[f"{value:g}" for value in ticks])
    colorbar.minorticks_off()
    colorbar.set_label("Cell area", fontsize=14, labelpad=5)
    colorbar.ax.tick_params(labelsize=12, colors=ink)
    colorbar.outline.set_linewidth(0.6)
    fig.savefig(OUTPUT / "grid.png", dpi=200, facecolor=background, bbox_inches="tight", pad_inches=0.08)
    fig.savefig(OUTPUT / "grid.pdf", facecolor=background, bbox_inches="tight", pad_inches=0.08)
    plt.close(fig)
    with (OUTPUT / "points.csv").open("w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["name", "x", "y", "cell_id"])
        writer.writerows(results)
        writer.writerow(["outside", 13.0, 4.0, ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--attempts", type=int, default=1, help="number of deterministic greedy variants to build")
    parser.add_argument("--regenerate-grid", action="store_true", help="resample the grid instead of reusing grid.geojson")
    parser.add_argument("--figure-only", action="store_true", help="redraw the saved grid and tree")
    args = parser.parse_args()
    if args.figure_only and (
        args.regenerate_grid or args.attempts != 1
        or not all((OUTPUT / name).exists() for name in ("grid.geojson", "tree.json"))
    ):
        parser.error("--figure-only requires a saved grid and tree and cannot rebuild them")
    if args.attempts < 1:
        parser.error("--attempts must be positive")
    if (OUTPUT / "grid.geojson").exists() and not args.regenerate_grid:
        print("Loading the existing polygonal grid...", flush=True)
        features = json.loads((OUTPUT / "grid.geojson").read_text())["features"]
        features.sort(key=lambda feature: feature["properties"]["cell_id"])
        if [feature["properties"]["cell_id"] for feature in features] != list(range(CELL_COUNT)):
            parser.error("grid.geojson must contain exactly the cell IDs 0 through 999")
        sites = np.array([feature["properties"]["site"] for feature in features])
        polygons = [np.array(feature["geometry"]["coordinates"][0][:-1]) for feature in features]
    else:
        print("Generating 1,000 clipped Voronoi cells...", flush=True)
        sites, polygons = make_grid()
    if args.figure_only:
        tree = json.loads((OUTPUT / "tree.json").read_text())
        print("Rendering the saved grid...", flush=True)
        draw_grid(polygons, tree)
        return
    print(f"Building {args.attempts} greedy tree(s)...", flush=True)
    locator = PointLocationTree(sites, polygons, WIDTH, HEIGHT, attempts=args.attempts)
    stats = write_data(sites, polygons, locator)
    print("Rendering the Matplotlib figure...", flush=True)
    draw_grid(polygons, locator.tree)
    print(json.dumps(stats, indent=2), flush=True)
    print(f"Saved grid, tree, SQL macros, and figures to {OUTPUT}", flush=True)


if __name__ == "__main__":
    main()
