#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["numpy==2.5.3", "scipy==1.18.1", "matplotlib==3.11.1"]
# ///
"""Generate 30,000 bounded Voronoi polyhedra, a point-location tree, and figures."""

import argparse
import csv
import gzip
import json
import os
from pathlib import Path
import tempfile
import time

os.environ.setdefault("MPLCONFIGDIR", str(Path(tempfile.gettempdir()) / "apart-matplotlib"))
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.collections import PolyCollection
from matplotlib.colors import LinearSegmentedColormap, LogNorm
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import numpy as np

from mesh import cell_points, make_mesh, make_sites, section
from point_location import PointLocationTree, locate

OUTPUT = Path(__file__).resolve().parent
BOUNDS = np.array([12.0, 8.0, 6.0])
CELL_COUNT = 30_000
SEED = 20260913


def write_tree(locator):
    tree = locator.tree
    with gzip.open(OUTPUT / "tree.json.gz", "wt", compresslevel=1) as handle:
        handle.write(json.dumps(tree, separators=(",", ":")) + "\n")

    def literal(value):
        if isinstance(value, list):
            return "[" + ",".join(literal(v) for v in value) + "]"
        return "NULL::INTEGER" if value is None else repr(value)

    sql = (
        "-- Generated by generate.py. Coordinates are DOUBLE; outside is NULL.\n"
        "LOAD apart;\n\nCREATE OR REPLACE MACRO unstructured_grid_3d_tree() AS {\n"
        + "    weights: " + literal(tree["weights"]) + "::DOUBLE[][],\n"
        + "    thresholds: " + literal(tree["thresholds"]) + "::DOUBLE[],\n"
        + "    children: " + literal(tree["children"]) + "::BIGINT[][],\n"
        + "    values: " + literal(tree["values"]) + "\n};\n\n"
        "CREATE OR REPLACE MACRO locate_cell_3d(x, y, z) AS\n"
        "    decision_tree(unstructured_grid_3d_tree(), x::DOUBLE, y::DOUBLE, z::DOUBLE);\n"
    )
    with gzip.open(OUTPUT / "grid.sql.gz", "wt", compresslevel=1) as handle:
        handle.write(sql)

    samples = [("A", 2.4, 5.5, 3.6), ("B", 6.0, 3.7, 1.85), ("C", 9.7, 2.5, 3.3)]
    rows = [(name, x, y, z, locate(tree, x, y, z)) for name, x, y, z in samples]
    with (OUTPUT / "points.csv").open("w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["name", "x", "y", "z", "cell_id"])
        writer.writerows(rows)
        writer.writerow(["outside", 13.0, 4.0, 3.0, ""])


def draw_grid(mesh, cells):
    background, ink = "#f7f4ec", "#173b49"
    cmap = LinearSegmentedColormap.from_list("estuary", ["#174e64", "#388d96", "#9cc5b3", "#edd9aa", "#d79061"])
    norm = LogNorm(vmin=float(np.quantile(mesh["volumes"], 0.01)), vmax=float(np.quantile(mesh["volumes"], 0.99)))
    colors = cmap(norm(mesh["volumes"]))
    plt.rcParams.update({
        "font.family": "DejaVu Sans", "font.size": 13,
        "text.color": ink, "axes.labelcolor": ink, "axes.labelsize": 15,
    })
    fig = plt.figure(figsize=(13.5, 7.5), facecolor=background, layout="constrained")
    panels = fig.add_gridspec(2, 2, width_ratios=(1.6, 1))
    ax = fig.add_subplot(panels[:, 0], projection="3d", computed_zorder=False)
    ax.set_facecolor(background)
    sites = mesh["sites"]
    kept = ~((sites[:, 0] > 6) & (sites[:, 1] < 4) & (sites[:, 2] > 3))
    a, b = mesh["face_cells"].T
    keep_a = kept[a]
    keep_b = (b >= 0) & kept[np.maximum(b, 0)]
    visible = np.flatnonzero(keep_a != keep_b)
    owner = np.where(keep_a[visible], a[visible], b[visible])
    offsets, indices = mesh["face_offsets"], mesh["face_vertices"]
    faces = [mesh["vertices"][indices[offsets[i]:offsets[i + 1]]] for i in visible]
    collection = Poly3DCollection(faces, facecolors=colors[owner], edgecolors=ink, linewidths=0.18,
                                 shade=True, antialiased=True)
    ax.add_collection3d(collection)
    ax.set(xlim=(0, BOUNDS[0]), ylim=(0, BOUNDS[1]), zlim=(0, BOUNDS[2]), xlabel="x", ylabel="y", zlabel="z")
    ax.set_box_aspect(BOUNDS.copy(), zoom=1.1)
    ax.view_init(elev=25, azim=-56)
    ax.set_proj_type("ortho")
    ax.grid(False)
    ax.set_xticks([0, 3, 6, 9, 12])
    ax.set_yticks([0, 2, 4, 6, 8])
    ax.set_zticks([0, 2, 4, 6])
    ax.tick_params(colors=ink, labelsize=13, pad=1)
    for axis in (ax.xaxis, ax.yaxis, ax.zaxis):
        axis.pane.fill = False
        axis.pane.set_edgecolor(background)

    axes = [ax]
    for row, (axis, value) in enumerate([(0, 6.0), (2, 3.0)]):
        polygons, ids = section(mesh, cells, axis, value)
        other = [i for i in range(3) if i != axis]
        panel = fig.add_subplot(panels[row, 1])
        axes.append(panel)
        panel.add_collection(PolyCollection(polygons, facecolors=colors[ids], edgecolors=ink, linewidths=0.25))
        panel.set(xlim=(0, BOUNDS[other[0]]), ylim=(0, BOUNDS[other[1]]),
                  xlabel="xyz"[other[0]], ylabel="xyz"[other[1]], aspect="equal")
        panel.set_title(f"{'xyz'[axis]} = {value:g}", fontsize=15, pad=8)
        panel.set_facecolor(background)
        panel.tick_params(colors=ink, labelsize=13)
        for spine in panel.spines.values():
            spine.set_color(ink)
            spine.set_linewidth(0.6)

    colorbar = fig.colorbar(
        plt.cm.ScalarMappable(norm=norm, cmap=cmap), ax=axes,
        orientation="horizontal", fraction=0.045, pad=0.04, shrink=0.6,
        aspect=45, extend="both",
    )
    ticks = [value for value in (0.001, 0.003, 0.01, 0.03, 0.1) if norm.vmin <= value <= norm.vmax]
    colorbar.set_ticks(ticks, labels=[f"{value:g}" for value in ticks])
    colorbar.minorticks_off()
    colorbar.set_label("Cell volume", fontsize=14, labelpad=5)
    colorbar.ax.tick_params(labelsize=12, colors=ink)
    colorbar.outline.set_linewidth(0.6)
    fig.savefig(OUTPUT / "grid.png", dpi=200, facecolor=background, bbox_inches="tight", pad_inches=0.08)
    fig.savefig(OUTPUT / "grid.pdf", facecolor=background, bbox_inches="tight", pad_inches=0.08)
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--regenerate-grid", action="store_true")
    parser.add_argument("--figure-only", action="store_true", help="redraw the saved grid")
    args = parser.parse_args()
    if args.figure_only and (args.regenerate_grid or not (OUTPUT / "grid.npz").exists()):
        parser.error("--figure-only requires an existing grid and cannot regenerate it")
    started = time.perf_counter()
    path = OUTPUT / "grid.npz"
    if path.exists() and not args.regenerate_grid:
        print("Loading the existing 3D polyhedral grid...", flush=True)
        with np.load(path, allow_pickle=False) as archive:
            mesh = dict(archive)
    else:
        print("Placing and smoothing 30,000 sites...", flush=True)
        sites = make_sites(CELL_COUNT, BOUNDS, SEED)
        print("Constructing the bounded Voronoi polyhedra...", flush=True)
        mesh = make_mesh(sites, BOUNDS)
        np.savez_compressed(path, **mesh)
    mesh_seconds = time.perf_counter() - started
    cells = cell_points(mesh)
    if args.figure_only:
        print("Rendering the saved grid...", flush=True)
        draw_grid(mesh, cells)
        return
    print(f"Mesh ready in {mesh_seconds:.2f} s; building the point-location tree...", flush=True)
    locator = PointLocationTree(mesh["sites"], cells, BOUNDS)
    print(f"Tree ready in {locator.build_seconds:.2f} s; writing artifacts...", flush=True)
    write_tree(locator)
    stats = {
        "seed": SEED, "cells": len(cells), "bounds": BOUNDS.tolist(),
        "geometry": "bounded 3D Voronoi cells, with one vertex-mean smoothing pass",
        "vertices": len(mesh["vertices"]), "faces": len(mesh["face_cells"]),
        "total_cell_volume": float(mesh["volumes"].sum()), "domain_volume": float(np.prod(BOUNDS)),
        "min_cell_volume": float(mesh["volumes"].min()), "max_cell_volume": float(mesh["volumes"].max()),
        "internal_nodes": len(locator.tree["weights"]), "distinct_leaf_values": len(locator.tree["values"]),
        "interior_leaf_occurrences": len(locator.leaf_depths),
        "min_interior_decisions": min(locator.leaf_depths), "max_interior_decisions": max(locator.leaf_depths),
        "depth_note": "structural path lengths; conservative cell bounds can leave unreachable branches",
        "domain_checks": 6, "mesh_load_or_generation_seconds": mesh_seconds,
        "tree_build_seconds": locator.build_seconds,
        "boundary_rule": "closed box, shared boundaries follow >= branches with double precision",
        "outside_value": None,
    }
    (OUTPUT / "metadata.json").write_text(json.dumps(stats, indent=2) + "\n")
    print("Rendering the cutaway and cross-sections...", flush=True)
    draw_grid(mesh, cells)
    print(json.dumps(stats, indent=2), flush=True)
    print(f"Saved grid, tree, SQL, and figures to {OUTPUT}", flush=True)


if __name__ == "__main__":
    main()
